[package]
name = "MUC-server"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.45", default-features = false, features = ["clock", "std"] }
uuid = { version = "1.23.3", features = ["v4"] }
anyhow = "1.0.102"
rusqlite = { version = "0.40.1", features = ["bundled", "uuid"] }
colored = "3.1.1"
dotenvy = "0.15.7"