[package]
name = "MUC-server"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.45", default-features = false, features = ["clock", "std"] }
uuid = { version = "1.23.5", features = ["v4"] }
anyhow = "1.0.103"
rusqlite = { version = "0.40.1", features = ["bundled", "uuid"] }
colored = "3.1.1"
dotenvy = "0.15.7"
argon2 = { version = "0.5.3", features = ["std"] }
password-hash = "0.6.1"
rand_core = "0.10.1"
dirs = "6.0.0"
ctrlc = "3.5.2"